### ISSUE TITLE
 Error for email reste with bootstrap3-v1.0 theme

### ISSUE THREAD

**Issue by upm127** [NateWr/bootstrap3#35] opened 2016-09-19 19:17 UTC
Registered user's email function not working with bootstrap them (we get this error : No user exists with the specified email address.) . but when i changed the theme to the default it is working fine.

Im using ojs 3:
http://sportuniversity.org/sport/index.php/ijaep/login/lostPassword

You may check by registering and then reset. if need i can send you account detail for journal manager.

Thank You

**Comment by NateWr** [comment] 2016-09-26 13:40
Thanks for reporting @upm127. I've flagged this as a bug so it will get investigated for a future release.

**Comment by Avernial** [comment] 2016-11-08 07:08
The cause of this error is a missing parameter `name="email"` in userLostPassword.tpl

`<input type="text" name="email" id="email" value="{$email|escape}" maxlength="32" required>`

**Comment by upm127** [comment] 2016-11-11 04:30
Dear Avernial
Please let me know, which line should be modified. I'm not familiar with this code. 
Thanks

**Comment by Avernial** [comment] 2016-11-11 05:03
Line 34 in the file `templates/frontend/pages/userLostPassword.tpl`. 
The line should be the: 
`<input type="email" name="email" class="form-control" id="login-email" placeholder="{translate key='user.login.registeredEmail'}" value="{$email|escape}" maxlenght="32" required>`

**Comment by NateWr** [comment] 2016-11-14 11:17
@Avernial Would you be willing to provide a Pull Request for this fix?

**Comment by Avernial** [comment] 2016-11-21 02:53
I've submited the pull request #45

**Comment by NateWr** [comment] 2016-11-21 12:39
Merged!

**Closed by NateWr** 2016-11-21 12:39 UTC
Labels: bug
